class NewMasterCode
{
  .....New code...
  .....New code...
  .....New code...
  .....New code...
}

class MasterCode
{
  ......master code......
  ......master code......
  ......master code......
  ......master code......
  ......master code......
}

